// Code generated by cmd/gen-manifest. DO NOT EDIT.
//
// Regenerate with `make manifest-gen`. The scope lists below are
// the union of:
//
//   1. Scopes required by every Slack API method called from pkg/cmd/...
//      (auto-derived via AST walk + spec lookup)
//   2. A baseline set of scopes the CLI wants regardless (resolver, auth
//      handshake, etc.) — see cmd/gen-manifest/main.go:baseline*Scopes
//
// Adding a slackapi.<Method>(...) call somewhere in pkg/cmd/ triggers an
// automatic scope update on the next `make manifest-gen`; CI's
// `make verify-gen` will fail if the manifest drifts.

package app

// appManifest is the canonical Slack app manifest used by `app create`
// and `app update`. The two consumer commands compose it as a JSON
// payload to apps.manifest.{create,update}.
//
// Methods this scope set covers (alphabetised):
//   - chat.delete
//   - chat.postMessage
//   - chat.update
//   - conversations.history
//   - conversations.info
//   - conversations.list
//   - conversations.replies
//   - files.completeUploadExternal
//   - files.getUploadURLExternal
//   - reactions.add
//   - reactions.get
//   - reactions.remove
//   - search.files
//   - search.messages
//   - users.info
//   - users.list

var appManifest = map[string]interface{}{
	"display_information": map[string]interface{}{
		"name":             "SlackBuzz CLI",
		"description":      "CLI tool for Slack messaging, channel management, and search",
		"background_color": "#1a1a2e",
	},
	"features": map[string]interface{}{
		"bot_user": map[string]interface{}{
			"display_name":  "SlackBuzz",
			"always_online": false,
		},
	},
	"oauth_config": map[string]interface{}{
		"scopes": map[string]interface{}{
			"bot": []string{
				"channels:history",
				"channels:read",
				"chat:write",
				"emoji:read",
				"files:read",
				"files:write",
				"groups:history",
				"groups:read",
				"im:history",
				"im:read",
				"mpim:history",
				"mpim:read",
				"reactions:read",
				"reactions:write",
				"search:read",
				"users:read",
			},
			"user": []string{
				"channels:history",
				"channels:read",
				"chat:write",
				"files:read",
				"files:write",
				"groups:history",
				"groups:read",
				"im:history",
				"im:read",
				"im:write",
				"mpim:history",
				"mpim:read",
				"reactions:read",
				"reactions:write",
				"search:read",
				"stars:read",
				"stars:write",
				"users.profile:read",
				"users.profile:write",
				"users:read",
			},
		},
	},
	"settings": map[string]interface{}{
		"org_deploy_enabled":     false,
		"socket_mode_enabled":    false,
		"token_rotation_enabled": false,
	},
}
