// Code generated by cmd/gen-api from Slack's Web API OpenAPI 2.0 spec.
// DO NOT EDIT — regenerate with `make api-gen`.

package slackapi

import (
	"context"
	"encoding/json"
	"net/url"
)

// Ensure imports are used.
var (
	_ = url.Values{}
	_ = context.Background
	_ = json.RawMessage{}
)

// AdminAppsApprove calls Slack's admin.apps.approve method.
//
// Required scopes (any one combination): admin.apps:write
func AdminAppsApprove(ctx context.Context, c *Client, params *AdminAppsApproveParams) (*AdminAppsApproveResponse, error) {
	var resp AdminAppsApproveResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.apps.approve", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminAppsApprovedList calls Slack's admin.apps.approved.list method.
//
// Required scopes (any one combination): admin.apps:read
func AdminAppsApprovedList(ctx context.Context, c *Client, params *AdminAppsApprovedListParams) (*AdminAppsApprovedListResponse, error) {
	var resp AdminAppsApprovedListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.apps.approved.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminAppsRequestsList calls Slack's admin.apps.requests.list method.
//
// Required scopes (any one combination): admin.apps:read
func AdminAppsRequestsList(ctx context.Context, c *Client, params *AdminAppsRequestsListParams) (*AdminAppsRequestsListResponse, error) {
	var resp AdminAppsRequestsListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.apps.requests.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminAppsRestrict calls Slack's admin.apps.restrict method.
//
// Required scopes (any one combination): admin.apps:write
func AdminAppsRestrict(ctx context.Context, c *Client, params *AdminAppsRestrictParams) (*AdminAppsRestrictResponse, error) {
	var resp AdminAppsRestrictResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.apps.restrict", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminAppsRestrictedList calls Slack's admin.apps.restricted.list method.
//
// Required scopes (any one combination): admin.apps:read
func AdminAppsRestrictedList(ctx context.Context, c *Client, params *AdminAppsRestrictedListParams) (*AdminAppsRestrictedListResponse, error) {
	var resp AdminAppsRestrictedListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.apps.restricted.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsArchive calls Slack's admin.conversations.archive method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsArchive(ctx context.Context, c *Client, params *AdminConversationsArchiveParams) (*AdminConversationsArchiveResponse, error) {
	var resp AdminConversationsArchiveResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.archive", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsConvertToPrivate calls Slack's admin.conversations.convertToPrivate method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsConvertToPrivate(ctx context.Context, c *Client, params *AdminConversationsConvertToPrivateParams) (*AdminConversationsConvertToPrivateResponse, error) {
	var resp AdminConversationsConvertToPrivateResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.convertToPrivate", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsCreate calls Slack's admin.conversations.create method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsCreate(ctx context.Context, c *Client, params *AdminConversationsCreateParams) (*AdminConversationsCreateResponse, error) {
	var resp AdminConversationsCreateResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.create", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsDelete calls Slack's admin.conversations.delete method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsDelete(ctx context.Context, c *Client, params *AdminConversationsDeleteParams) (*AdminConversationsDeleteResponse, error) {
	var resp AdminConversationsDeleteResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.delete", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsDisconnectShared calls Slack's admin.conversations.disconnectShared method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsDisconnectShared(ctx context.Context, c *Client, params *AdminConversationsDisconnectSharedParams) (*AdminConversationsDisconnectSharedResponse, error) {
	var resp AdminConversationsDisconnectSharedResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.disconnectShared", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsEkmListOriginalConnectedChannelInfo calls Slack's admin.conversations.ekm.listOriginalConnectedChannelInfo method.
//
// Required scopes (any one combination): admin.conversations:read
func AdminConversationsEkmListOriginalConnectedChannelInfo(ctx context.Context, c *Client, params *AdminConversationsEkmListOriginalConnectedChannelInfoParams) (*AdminConversationsEkmListOriginalConnectedChannelInfoResponse, error) {
	var resp AdminConversationsEkmListOriginalConnectedChannelInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.ekm.listOriginalConnectedChannelInfo", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsGetConversationPrefs calls Slack's admin.conversations.getConversationPrefs method.
//
// Required scopes (any one combination): admin.conversations:read
func AdminConversationsGetConversationPrefs(ctx context.Context, c *Client, params *AdminConversationsGetConversationPrefsParams) (*AdminConversationsGetConversationPrefsResponse, error) {
	var resp AdminConversationsGetConversationPrefsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.getConversationPrefs", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsGetTeams calls Slack's admin.conversations.getTeams method.
//
// Required scopes (any one combination): admin.conversations:read
func AdminConversationsGetTeams(ctx context.Context, c *Client, params *AdminConversationsGetTeamsParams) (*AdminConversationsGetTeamsResponse, error) {
	var resp AdminConversationsGetTeamsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.getTeams", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsInvite calls Slack's admin.conversations.invite method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsInvite(ctx context.Context, c *Client, params *AdminConversationsInviteParams) (*AdminConversationsInviteResponse, error) {
	var resp AdminConversationsInviteResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.invite", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsRename calls Slack's admin.conversations.rename method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsRename(ctx context.Context, c *Client, params *AdminConversationsRenameParams) (*AdminConversationsRenameResponse, error) {
	var resp AdminConversationsRenameResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.rename", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsRestrictAccessAddGroup calls Slack's admin.conversations.restrictAccess.addGroup method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsRestrictAccessAddGroup(ctx context.Context, c *Client, params *AdminConversationsRestrictAccessAddGroupParams) (*AdminConversationsRestrictAccessAddGroupResponse, error) {
	var resp AdminConversationsRestrictAccessAddGroupResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.restrictAccess.addGroup", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsRestrictAccessListGroups calls Slack's admin.conversations.restrictAccess.listGroups method.
//
// Required scopes (any one combination): admin.conversations:read
func AdminConversationsRestrictAccessListGroups(ctx context.Context, c *Client, params *AdminConversationsRestrictAccessListGroupsParams) (*AdminConversationsRestrictAccessListGroupsResponse, error) {
	var resp AdminConversationsRestrictAccessListGroupsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.restrictAccess.listGroups", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsRestrictAccessRemoveGroup calls Slack's admin.conversations.restrictAccess.removeGroup method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsRestrictAccessRemoveGroup(ctx context.Context, c *Client, params *AdminConversationsRestrictAccessRemoveGroupParams) (*AdminConversationsRestrictAccessRemoveGroupResponse, error) {
	var resp AdminConversationsRestrictAccessRemoveGroupResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.restrictAccess.removeGroup", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsSearch calls Slack's admin.conversations.search method.
//
// Required scopes (any one combination): admin.conversations:read
func AdminConversationsSearch(ctx context.Context, c *Client, params *AdminConversationsSearchParams) (*AdminConversationsSearchResponse, error) {
	var resp AdminConversationsSearchResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.search", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsSetConversationPrefs calls Slack's admin.conversations.setConversationPrefs method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsSetConversationPrefs(ctx context.Context, c *Client, params *AdminConversationsSetConversationPrefsParams) (*AdminConversationsSetConversationPrefsResponse, error) {
	var resp AdminConversationsSetConversationPrefsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.setConversationPrefs", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsSetTeams calls Slack's admin.conversations.setTeams method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsSetTeams(ctx context.Context, c *Client, params *AdminConversationsSetTeamsParams) (*AdminConversationsSetTeamsResponse, error) {
	var resp AdminConversationsSetTeamsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.setTeams", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminConversationsUnarchive calls Slack's admin.conversations.unarchive method.
//
// Required scopes (any one combination): admin.conversations:write
func AdminConversationsUnarchive(ctx context.Context, c *Client, params *AdminConversationsUnarchiveParams) (*AdminConversationsUnarchiveResponse, error) {
	var resp AdminConversationsUnarchiveResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.conversations.unarchive", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminEmojiAdd calls Slack's admin.emoji.add method.
//
// Required scopes (any one combination): admin.teams:write
func AdminEmojiAdd(ctx context.Context, c *Client, params *AdminEmojiAddParams) (*AdminEmojiAddResponse, error) {
	var resp AdminEmojiAddResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.emoji.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminEmojiAddAlias calls Slack's admin.emoji.addAlias method.
//
// Required scopes (any one combination): admin.teams:write
func AdminEmojiAddAlias(ctx context.Context, c *Client, params *AdminEmojiAddAliasParams) (*AdminEmojiAddAliasResponse, error) {
	var resp AdminEmojiAddAliasResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.emoji.addAlias", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminEmojiList calls Slack's admin.emoji.list method.
//
// Required scopes (any one combination): admin.teams:read
func AdminEmojiList(ctx context.Context, c *Client, params *AdminEmojiListParams) (*AdminEmojiListResponse, error) {
	var resp AdminEmojiListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.emoji.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminEmojiRemove calls Slack's admin.emoji.remove method.
//
// Required scopes (any one combination): admin.teams:write
func AdminEmojiRemove(ctx context.Context, c *Client, params *AdminEmojiRemoveParams) (*AdminEmojiRemoveResponse, error) {
	var resp AdminEmojiRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.emoji.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminEmojiRename calls Slack's admin.emoji.rename method.
//
// Required scopes (any one combination): admin.teams:write
func AdminEmojiRename(ctx context.Context, c *Client, params *AdminEmojiRenameParams) (*AdminEmojiRenameResponse, error) {
	var resp AdminEmojiRenameResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.emoji.rename", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminInviteRequestsApprove calls Slack's admin.inviteRequests.approve method.
//
// Required scopes (any one combination): admin.invites:write
func AdminInviteRequestsApprove(ctx context.Context, c *Client, params *AdminInviteRequestsApproveParams) (*AdminInviteRequestsApproveResponse, error) {
	var resp AdminInviteRequestsApproveResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.inviteRequests.approve", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminInviteRequestsApprovedList calls Slack's admin.inviteRequests.approved.list method.
//
// Required scopes (any one combination): admin.invites:read
func AdminInviteRequestsApprovedList(ctx context.Context, c *Client, params *AdminInviteRequestsApprovedListParams) (*AdminInviteRequestsApprovedListResponse, error) {
	var resp AdminInviteRequestsApprovedListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.inviteRequests.approved.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminInviteRequestsDeniedList calls Slack's admin.inviteRequests.denied.list method.
//
// Required scopes (any one combination): admin.invites:read
func AdminInviteRequestsDeniedList(ctx context.Context, c *Client, params *AdminInviteRequestsDeniedListParams) (*AdminInviteRequestsDeniedListResponse, error) {
	var resp AdminInviteRequestsDeniedListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.inviteRequests.denied.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminInviteRequestsDeny calls Slack's admin.inviteRequests.deny method.
//
// Required scopes (any one combination): admin.invites:write
func AdminInviteRequestsDeny(ctx context.Context, c *Client, params *AdminInviteRequestsDenyParams) (*AdminInviteRequestsDenyResponse, error) {
	var resp AdminInviteRequestsDenyResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.inviteRequests.deny", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminInviteRequestsList calls Slack's admin.inviteRequests.list method.
//
// Required scopes (any one combination): admin.invites:read
func AdminInviteRequestsList(ctx context.Context, c *Client, params *AdminInviteRequestsListParams) (*AdminInviteRequestsListResponse, error) {
	var resp AdminInviteRequestsListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.inviteRequests.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsAdminsList calls Slack's admin.teams.admins.list method.
//
// Required scopes (any one combination): admin.teams:read
func AdminTeamsAdminsList(ctx context.Context, c *Client, params *AdminTeamsAdminsListParams) (*AdminTeamsAdminsListResponse, error) {
	var resp AdminTeamsAdminsListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.admins.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsCreate calls Slack's admin.teams.create method.
//
// Required scopes (any one combination): admin.teams:write
func AdminTeamsCreate(ctx context.Context, c *Client, params *AdminTeamsCreateParams) (*AdminTeamsCreateResponse, error) {
	var resp AdminTeamsCreateResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.create", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsList calls Slack's admin.teams.list method.
//
// Required scopes (any one combination): admin.teams:read
func AdminTeamsList(ctx context.Context, c *Client, params *AdminTeamsListParams) (*AdminTeamsListResponse, error) {
	var resp AdminTeamsListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsOwnersList calls Slack's admin.teams.owners.list method.
//
// Required scopes (any one combination): admin.teams:read
func AdminTeamsOwnersList(ctx context.Context, c *Client, params *AdminTeamsOwnersListParams) (*AdminTeamsOwnersListResponse, error) {
	var resp AdminTeamsOwnersListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.owners.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsSettingsInfo calls Slack's admin.teams.settings.info method.
//
// Required scopes (any one combination): admin.teams:read
func AdminTeamsSettingsInfo(ctx context.Context, c *Client, params *AdminTeamsSettingsInfoParams) (*AdminTeamsSettingsInfoResponse, error) {
	var resp AdminTeamsSettingsInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.settings.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsSettingsSetDefaultChannels calls Slack's admin.teams.settings.setDefaultChannels method.
//
// Required scopes (any one combination): admin.teams:write
func AdminTeamsSettingsSetDefaultChannels(ctx context.Context, c *Client, params *AdminTeamsSettingsSetDefaultChannelsParams) (*AdminTeamsSettingsSetDefaultChannelsResponse, error) {
	var resp AdminTeamsSettingsSetDefaultChannelsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.settings.setDefaultChannels", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsSettingsSetDescription calls Slack's admin.teams.settings.setDescription method.
//
// Required scopes (any one combination): admin.teams:write
func AdminTeamsSettingsSetDescription(ctx context.Context, c *Client, params *AdminTeamsSettingsSetDescriptionParams) (*AdminTeamsSettingsSetDescriptionResponse, error) {
	var resp AdminTeamsSettingsSetDescriptionResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.settings.setDescription", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsSettingsSetDiscoverability calls Slack's admin.teams.settings.setDiscoverability method.
//
// Required scopes (any one combination): admin.teams:write
func AdminTeamsSettingsSetDiscoverability(ctx context.Context, c *Client, params *AdminTeamsSettingsSetDiscoverabilityParams) (*AdminTeamsSettingsSetDiscoverabilityResponse, error) {
	var resp AdminTeamsSettingsSetDiscoverabilityResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.settings.setDiscoverability", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsSettingsSetIcon calls Slack's admin.teams.settings.setIcon method.
//
// Required scopes (any one combination): admin.teams:write
func AdminTeamsSettingsSetIcon(ctx context.Context, c *Client, params *AdminTeamsSettingsSetIconParams) (*AdminTeamsSettingsSetIconResponse, error) {
	var resp AdminTeamsSettingsSetIconResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.settings.setIcon", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminTeamsSettingsSetName calls Slack's admin.teams.settings.setName method.
//
// Required scopes (any one combination): admin.teams:write
func AdminTeamsSettingsSetName(ctx context.Context, c *Client, params *AdminTeamsSettingsSetNameParams) (*AdminTeamsSettingsSetNameResponse, error) {
	var resp AdminTeamsSettingsSetNameResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.teams.settings.setName", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsergroupsAddChannels calls Slack's admin.usergroups.addChannels method.
//
// Required scopes (any one combination): admin.usergroups:write
func AdminUsergroupsAddChannels(ctx context.Context, c *Client, params *AdminUsergroupsAddChannelsParams) (*AdminUsergroupsAddChannelsResponse, error) {
	var resp AdminUsergroupsAddChannelsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.usergroups.addChannels", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsergroupsAddTeams calls Slack's admin.usergroups.addTeams method.
//
// Required scopes (any one combination): admin.teams:write
func AdminUsergroupsAddTeams(ctx context.Context, c *Client, params *AdminUsergroupsAddTeamsParams) (*AdminUsergroupsAddTeamsResponse, error) {
	var resp AdminUsergroupsAddTeamsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.usergroups.addTeams", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsergroupsListChannels calls Slack's admin.usergroups.listChannels method.
//
// Required scopes (any one combination): admin.usergroups:read
func AdminUsergroupsListChannels(ctx context.Context, c *Client, params *AdminUsergroupsListChannelsParams) (*AdminUsergroupsListChannelsResponse, error) {
	var resp AdminUsergroupsListChannelsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.usergroups.listChannels", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsergroupsRemoveChannels calls Slack's admin.usergroups.removeChannels method.
//
// Required scopes (any one combination): admin.usergroups:write
func AdminUsergroupsRemoveChannels(ctx context.Context, c *Client, params *AdminUsergroupsRemoveChannelsParams) (*AdminUsergroupsRemoveChannelsResponse, error) {
	var resp AdminUsergroupsRemoveChannelsResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.usergroups.removeChannels", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersAssign calls Slack's admin.users.assign method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersAssign(ctx context.Context, c *Client, params *AdminUsersAssignParams) (*AdminUsersAssignResponse, error) {
	var resp AdminUsersAssignResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.assign", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersInvite calls Slack's admin.users.invite method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersInvite(ctx context.Context, c *Client, params *AdminUsersInviteParams) (*AdminUsersInviteResponse, error) {
	var resp AdminUsersInviteResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.invite", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersList calls Slack's admin.users.list method.
//
// Required scopes (any one combination): admin.users:read
func AdminUsersList(ctx context.Context, c *Client, params *AdminUsersListParams) (*AdminUsersListResponse, error) {
	var resp AdminUsersListResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersRemove calls Slack's admin.users.remove method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersRemove(ctx context.Context, c *Client, params *AdminUsersRemoveParams) (*AdminUsersRemoveResponse, error) {
	var resp AdminUsersRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersSessionInvalidate calls Slack's admin.users.session.invalidate method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersSessionInvalidate(ctx context.Context, c *Client, params *AdminUsersSessionInvalidateParams) (*AdminUsersSessionInvalidateResponse, error) {
	var resp AdminUsersSessionInvalidateResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.session.invalidate", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersSessionReset calls Slack's admin.users.session.reset method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersSessionReset(ctx context.Context, c *Client, params *AdminUsersSessionResetParams) (*AdminUsersSessionResetResponse, error) {
	var resp AdminUsersSessionResetResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.session.reset", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersSetAdmin calls Slack's admin.users.setAdmin method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersSetAdmin(ctx context.Context, c *Client, params *AdminUsersSetAdminParams) (*AdminUsersSetAdminResponse, error) {
	var resp AdminUsersSetAdminResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.setAdmin", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersSetExpiration calls Slack's admin.users.setExpiration method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersSetExpiration(ctx context.Context, c *Client, params *AdminUsersSetExpirationParams) (*AdminUsersSetExpirationResponse, error) {
	var resp AdminUsersSetExpirationResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.setExpiration", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersSetOwner calls Slack's admin.users.setOwner method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersSetOwner(ctx context.Context, c *Client, params *AdminUsersSetOwnerParams) (*AdminUsersSetOwnerResponse, error) {
	var resp AdminUsersSetOwnerResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.setOwner", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AdminUsersSetRegular calls Slack's admin.users.setRegular method.
//
// Required scopes (any one combination): admin.users:write
func AdminUsersSetRegular(ctx context.Context, c *Client, params *AdminUsersSetRegularParams) (*AdminUsersSetRegularResponse, error) {
	var resp AdminUsersSetRegularResponse
	form := params.values()
	body, err := Do(ctx, c, "admin.users.setRegular", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// APITest calls Slack's api.test method.
//
// Required scopes (any one combination): none
func APITest(ctx context.Context, c *Client, params *APITestParams) (*APITestResponse, error) {
	var resp APITestResponse
	form := params.values()
	body, err := Do(ctx, c, "api.test", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsEventAuthorizationsList calls Slack's apps.event.authorizations.list method.
//
// Required scopes (any one combination): authorizations:read
func AppsEventAuthorizationsList(ctx context.Context, c *Client, params *AppsEventAuthorizationsListParams) (*AppsEventAuthorizationsListResponse, error) {
	var resp AppsEventAuthorizationsListResponse
	form := params.values()
	body, err := Do(ctx, c, "apps.event.authorizations.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsPermissionsInfo calls Slack's apps.permissions.info method.
//
// Required scopes (any one combination): none
func AppsPermissionsInfo(ctx context.Context, c *Client) (*AppsPermissionsInfoResponse, error) {
	var resp AppsPermissionsInfoResponse
	form := url.Values{}
	body, err := Do(ctx, c, "apps.permissions.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsPermissionsRequest calls Slack's apps.permissions.request method.
//
// Required scopes (any one combination): none
func AppsPermissionsRequest(ctx context.Context, c *Client, params *AppsPermissionsRequestParams) (*AppsPermissionsRequestResponse, error) {
	var resp AppsPermissionsRequestResponse
	form := params.values()
	body, err := Do(ctx, c, "apps.permissions.request", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsPermissionsResourcesList calls Slack's apps.permissions.resources.list method.
//
// Required scopes (any one combination): none
func AppsPermissionsResourcesList(ctx context.Context, c *Client, params *AppsPermissionsResourcesListParams) (*AppsPermissionsResourcesListResponse, error) {
	var resp AppsPermissionsResourcesListResponse
	form := params.values()
	body, err := Do(ctx, c, "apps.permissions.resources.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsPermissionsScopesList calls Slack's apps.permissions.scopes.list method.
//
// Required scopes (any one combination): none
func AppsPermissionsScopesList(ctx context.Context, c *Client) (*AppsPermissionsScopesListResponse, error) {
	var resp AppsPermissionsScopesListResponse
	form := url.Values{}
	body, err := Do(ctx, c, "apps.permissions.scopes.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsPermissionsUsersList calls Slack's apps.permissions.users.list method.
//
// Required scopes (any one combination): none
func AppsPermissionsUsersList(ctx context.Context, c *Client, params *AppsPermissionsUsersListParams) (*AppsPermissionsUsersListResponse, error) {
	var resp AppsPermissionsUsersListResponse
	form := params.values()
	body, err := Do(ctx, c, "apps.permissions.users.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsPermissionsUsersRequest calls Slack's apps.permissions.users.request method.
//
// Required scopes (any one combination): none
func AppsPermissionsUsersRequest(ctx context.Context, c *Client, params *AppsPermissionsUsersRequestParams) (*AppsPermissionsUsersRequestResponse, error) {
	var resp AppsPermissionsUsersRequestResponse
	form := params.values()
	body, err := Do(ctx, c, "apps.permissions.users.request", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AppsUninstall calls Slack's apps.uninstall method.
//
// Required scopes (any one combination): none
func AppsUninstall(ctx context.Context, c *Client, params *AppsUninstallParams) (*AppsUninstallResponse, error) {
	var resp AppsUninstallResponse
	form := params.values()
	body, err := Do(ctx, c, "apps.uninstall", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AuthRevoke calls Slack's auth.revoke method.
//
// Required scopes (any one combination): none
func AuthRevoke(ctx context.Context, c *Client, params *AuthRevokeParams) (*AuthRevokeResponse, error) {
	var resp AuthRevokeResponse
	form := params.values()
	body, err := Do(ctx, c, "auth.revoke", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// AuthTest calls Slack's auth.test method.
//
// Required scopes (any one combination): none
func AuthTest(ctx context.Context, c *Client) (*AuthTestResponse, error) {
	var resp AuthTestResponse
	form := url.Values{}
	body, err := Do(ctx, c, "auth.test", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// BotsInfo calls Slack's bots.info method.
//
// Required scopes (any one combination): users:read
func BotsInfo(ctx context.Context, c *Client, params *BotsInfoParams) (*BotsInfoResponse, error) {
	var resp BotsInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "bots.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// CallsAdd calls Slack's calls.add method.
//
// Required scopes (any one combination): calls:write
func CallsAdd(ctx context.Context, c *Client, params *CallsAddParams) (*CallsAddResponse, error) {
	var resp CallsAddResponse
	form := params.values()
	body, err := Do(ctx, c, "calls.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// CallsEnd calls Slack's calls.end method.
//
// Required scopes (any one combination): calls:write
func CallsEnd(ctx context.Context, c *Client, params *CallsEndParams) (*CallsEndResponse, error) {
	var resp CallsEndResponse
	form := params.values()
	body, err := Do(ctx, c, "calls.end", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// CallsInfo calls Slack's calls.info method.
//
// Required scopes (any one combination): calls:read
func CallsInfo(ctx context.Context, c *Client, params *CallsInfoParams) (*CallsInfoResponse, error) {
	var resp CallsInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "calls.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// CallsParticipantsAdd calls Slack's calls.participants.add method.
//
// Required scopes (any one combination): calls:write
func CallsParticipantsAdd(ctx context.Context, c *Client, params *CallsParticipantsAddParams) (*CallsParticipantsAddResponse, error) {
	var resp CallsParticipantsAddResponse
	form := params.values()
	body, err := Do(ctx, c, "calls.participants.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// CallsParticipantsRemove calls Slack's calls.participants.remove method.
//
// Required scopes (any one combination): calls:write
func CallsParticipantsRemove(ctx context.Context, c *Client, params *CallsParticipantsRemoveParams) (*CallsParticipantsRemoveResponse, error) {
	var resp CallsParticipantsRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "calls.participants.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// CallsUpdate calls Slack's calls.update method.
//
// Required scopes (any one combination): calls:write
func CallsUpdate(ctx context.Context, c *Client, params *CallsUpdateParams) (*CallsUpdateResponse, error) {
	var resp CallsUpdateResponse
	form := params.values()
	body, err := Do(ctx, c, "calls.update", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatDelete calls Slack's chat.delete method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatDelete(ctx context.Context, c *Client, params *ChatDeleteParams) (*ChatDeleteResponse, error) {
	var resp ChatDeleteResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.delete", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatDeleteScheduledMessage calls Slack's chat.deleteScheduledMessage method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatDeleteScheduledMessage(ctx context.Context, c *Client, params *ChatDeleteScheduledMessageParams) (*ChatDeleteScheduledMessageResponse, error) {
	var resp ChatDeleteScheduledMessageResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.deleteScheduledMessage", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatGetPermalink calls Slack's chat.getPermalink method.
//
// Required scopes (any one combination): none
func ChatGetPermalink(ctx context.Context, c *Client, params *ChatGetPermalinkParams) (*ChatGetPermalinkResponse, error) {
	var resp ChatGetPermalinkResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.getPermalink", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatMeMessage calls Slack's chat.meMessage method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatMeMessage(ctx context.Context, c *Client, params *ChatMeMessageParams) (*ChatMeMessageResponse, error) {
	var resp ChatMeMessageResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.meMessage", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatPostEphemeral calls Slack's chat.postEphemeral method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatPostEphemeral(ctx context.Context, c *Client, params *ChatPostEphemeralParams) (*ChatPostEphemeralResponse, error) {
	var resp ChatPostEphemeralResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.postEphemeral", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatPostMessage calls Slack's chat.postMessage method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatPostMessage(ctx context.Context, c *Client, params *ChatPostMessageParams) (*ChatPostMessageResponse, error) {
	var resp ChatPostMessageResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.postMessage", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatScheduleMessage calls Slack's chat.scheduleMessage method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatScheduleMessage(ctx context.Context, c *Client, params *ChatScheduleMessageParams) (*ChatScheduleMessageResponse, error) {
	var resp ChatScheduleMessageResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.scheduleMessage", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatScheduledMessagesList calls Slack's chat.scheduledMessages.list method.
//
// Required scopes (any one combination): none
func ChatScheduledMessagesList(ctx context.Context, c *Client, params *ChatScheduledMessagesListParams) (*ChatScheduledMessagesListResponse, error) {
	var resp ChatScheduledMessagesListResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.scheduledMessages.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatUnfurl calls Slack's chat.unfurl method.
//
// Required scopes (any one combination): links:write
func ChatUnfurl(ctx context.Context, c *Client, params *ChatUnfurlParams) (*ChatUnfurlResponse, error) {
	var resp ChatUnfurlResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.unfurl", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ChatUpdate calls Slack's chat.update method.
//
// Required scopes (any one combination): chat:write:bot, chat:write:user
func ChatUpdate(ctx context.Context, c *Client, params *ChatUpdateParams) (*ChatUpdateResponse, error) {
	var resp ChatUpdateResponse
	form := params.values()
	body, err := Do(ctx, c, "chat.update", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsArchive calls Slack's conversations.archive method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsArchive(ctx context.Context, c *Client, params *ConversationsArchiveParams) (*ConversationsArchiveResponse, error) {
	var resp ConversationsArchiveResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.archive", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsClose calls Slack's conversations.close method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsClose(ctx context.Context, c *Client, params *ConversationsCloseParams) (*ConversationsCloseResponse, error) {
	var resp ConversationsCloseResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.close", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsCreate calls Slack's conversations.create method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsCreate(ctx context.Context, c *Client, params *ConversationsCreateParams) (*ConversationsCreateResponse, error) {
	var resp ConversationsCreateResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.create", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsHistory calls Slack's conversations.history method.
//
// Required scopes (any one combination): channels:history, groups:history, im:history, mpim:history
func ConversationsHistory(ctx context.Context, c *Client, params *ConversationsHistoryParams) (*ConversationsHistoryResponse, error) {
	var resp ConversationsHistoryResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.history", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsInfo calls Slack's conversations.info method.
//
// Required scopes (any one combination): channels:read, groups:read, im:read, mpim:read
func ConversationsInfo(ctx context.Context, c *Client, params *ConversationsInfoParams) (*ConversationsInfoResponse, error) {
	var resp ConversationsInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsInvite calls Slack's conversations.invite method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsInvite(ctx context.Context, c *Client, params *ConversationsInviteParams) (*ConversationsInviteResponse, error) {
	var resp ConversationsInviteResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.invite", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsJoin calls Slack's conversations.join method.
//
// Required scopes (any one combination): channels:write
func ConversationsJoin(ctx context.Context, c *Client, params *ConversationsJoinParams) (*ConversationsJoinResponse, error) {
	var resp ConversationsJoinResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.join", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsKick calls Slack's conversations.kick method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsKick(ctx context.Context, c *Client, params *ConversationsKickParams) (*ConversationsKickResponse, error) {
	var resp ConversationsKickResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.kick", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsLeave calls Slack's conversations.leave method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsLeave(ctx context.Context, c *Client, params *ConversationsLeaveParams) (*ConversationsLeaveResponse, error) {
	var resp ConversationsLeaveResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.leave", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsList calls Slack's conversations.list method.
//
// Required scopes (any one combination): channels:read, groups:read, im:read, mpim:read
func ConversationsList(ctx context.Context, c *Client, params *ConversationsListParams) (*ConversationsListResponse, error) {
	var resp ConversationsListResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsMark calls Slack's conversations.mark method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsMark(ctx context.Context, c *Client, params *ConversationsMarkParams) (*ConversationsMarkResponse, error) {
	var resp ConversationsMarkResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.mark", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsMembers calls Slack's conversations.members method.
//
// Required scopes (any one combination): channels:read, groups:read, im:read, mpim:read
func ConversationsMembers(ctx context.Context, c *Client, params *ConversationsMembersParams) (*ConversationsMembersResponse, error) {
	var resp ConversationsMembersResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.members", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsOpen calls Slack's conversations.open method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsOpen(ctx context.Context, c *Client, params *ConversationsOpenParams) (*ConversationsOpenResponse, error) {
	var resp ConversationsOpenResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.open", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsRename calls Slack's conversations.rename method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsRename(ctx context.Context, c *Client, params *ConversationsRenameParams) (*ConversationsRenameResponse, error) {
	var resp ConversationsRenameResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.rename", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsReplies calls Slack's conversations.replies method.
//
// Required scopes (any one combination): channels:history, groups:history, im:history, mpim:history
func ConversationsReplies(ctx context.Context, c *Client, params *ConversationsRepliesParams) (*ConversationsRepliesResponse, error) {
	var resp ConversationsRepliesResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.replies", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsSetPurpose calls Slack's conversations.setPurpose method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsSetPurpose(ctx context.Context, c *Client, params *ConversationsSetPurposeParams) (*ConversationsSetPurposeResponse, error) {
	var resp ConversationsSetPurposeResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.setPurpose", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsSetTopic calls Slack's conversations.setTopic method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsSetTopic(ctx context.Context, c *Client, params *ConversationsSetTopicParams) (*ConversationsSetTopicResponse, error) {
	var resp ConversationsSetTopicResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.setTopic", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ConversationsUnarchive calls Slack's conversations.unarchive method.
//
// Required scopes (any one combination): channels:write, groups:write, im:write, mpim:write
func ConversationsUnarchive(ctx context.Context, c *Client, params *ConversationsUnarchiveParams) (*ConversationsUnarchiveResponse, error) {
	var resp ConversationsUnarchiveResponse
	form := params.values()
	body, err := Do(ctx, c, "conversations.unarchive", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// DialogOpen calls Slack's dialog.open method.
//
// Required scopes (any one combination): none
func DialogOpen(ctx context.Context, c *Client, params *DialogOpenParams) (*DialogOpenResponse, error) {
	var resp DialogOpenResponse
	form := params.values()
	body, err := Do(ctx, c, "dialog.open", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// DndEndDnd calls Slack's dnd.endDnd method.
//
// Required scopes (any one combination): dnd:write
func DndEndDnd(ctx context.Context, c *Client) (*DndEndDndResponse, error) {
	var resp DndEndDndResponse
	form := url.Values{}
	body, err := Do(ctx, c, "dnd.endDnd", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// DndEndSnooze calls Slack's dnd.endSnooze method.
//
// Required scopes (any one combination): dnd:write
func DndEndSnooze(ctx context.Context, c *Client) (*DndEndSnoozeResponse, error) {
	var resp DndEndSnoozeResponse
	form := url.Values{}
	body, err := Do(ctx, c, "dnd.endSnooze", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// DndInfo calls Slack's dnd.info method.
//
// Required scopes (any one combination): dnd:read
func DndInfo(ctx context.Context, c *Client, params *DndInfoParams) (*DndInfoResponse, error) {
	var resp DndInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "dnd.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// DndSetSnooze calls Slack's dnd.setSnooze method.
//
// Required scopes (any one combination): dnd:write
func DndSetSnooze(ctx context.Context, c *Client, params *DndSetSnoozeParams) (*DndSetSnoozeResponse, error) {
	var resp DndSetSnoozeResponse
	form := params.values()
	body, err := Do(ctx, c, "dnd.setSnooze", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// DndTeamInfo calls Slack's dnd.teamInfo method.
//
// Required scopes (any one combination): dnd:read
func DndTeamInfo(ctx context.Context, c *Client, params *DndTeamInfoParams) (*DndTeamInfoResponse, error) {
	var resp DndTeamInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "dnd.teamInfo", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// EmojiList calls Slack's emoji.list method.
//
// Required scopes (any one combination): emoji:read
func EmojiList(ctx context.Context, c *Client) (*EmojiListResponse, error) {
	var resp EmojiListResponse
	form := url.Values{}
	body, err := Do(ctx, c, "emoji.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesCommentsDelete calls Slack's files.comments.delete method.
//
// Required scopes (any one combination): files:write:user
func FilesCommentsDelete(ctx context.Context, c *Client, params *FilesCommentsDeleteParams) (*FilesCommentsDeleteResponse, error) {
	var resp FilesCommentsDeleteResponse
	form := params.values()
	body, err := Do(ctx, c, "files.comments.delete", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesDelete calls Slack's files.delete method.
//
// Required scopes (any one combination): files:write:user
func FilesDelete(ctx context.Context, c *Client, params *FilesDeleteParams) (*FilesDeleteResponse, error) {
	var resp FilesDeleteResponse
	form := params.values()
	body, err := Do(ctx, c, "files.delete", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesInfo calls Slack's files.info method.
//
// Required scopes (any one combination): files:read
func FilesInfo(ctx context.Context, c *Client, params *FilesInfoParams) (*FilesInfoResponse, error) {
	var resp FilesInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "files.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesList calls Slack's files.list method.
//
// Required scopes (any one combination): files:read
func FilesList(ctx context.Context, c *Client, params *FilesListParams) (*FilesListResponse, error) {
	var resp FilesListResponse
	form := params.values()
	body, err := Do(ctx, c, "files.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRemoteAdd calls Slack's files.remote.add method.
//
// Required scopes (any one combination): remote_files:write
func FilesRemoteAdd(ctx context.Context, c *Client, params *FilesRemoteAddParams) (*FilesRemoteAddResponse, error) {
	var resp FilesRemoteAddResponse
	form := params.values()
	body, err := Do(ctx, c, "files.remote.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRemoteInfo calls Slack's files.remote.info method.
//
// Required scopes (any one combination): remote_files:read
func FilesRemoteInfo(ctx context.Context, c *Client, params *FilesRemoteInfoParams) (*FilesRemoteInfoResponse, error) {
	var resp FilesRemoteInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "files.remote.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRemoteList calls Slack's files.remote.list method.
//
// Required scopes (any one combination): remote_files:read
func FilesRemoteList(ctx context.Context, c *Client, params *FilesRemoteListParams) (*FilesRemoteListResponse, error) {
	var resp FilesRemoteListResponse
	form := params.values()
	body, err := Do(ctx, c, "files.remote.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRemoteRemove calls Slack's files.remote.remove method.
//
// Required scopes (any one combination): remote_files:write
func FilesRemoteRemove(ctx context.Context, c *Client, params *FilesRemoteRemoveParams) (*FilesRemoteRemoveResponse, error) {
	var resp FilesRemoteRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "files.remote.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRemoteShare calls Slack's files.remote.share method.
//
// Required scopes (any one combination): remote_files:share
func FilesRemoteShare(ctx context.Context, c *Client, params *FilesRemoteShareParams) (*FilesRemoteShareResponse, error) {
	var resp FilesRemoteShareResponse
	form := params.values()
	body, err := Do(ctx, c, "files.remote.share", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRemoteUpdate calls Slack's files.remote.update method.
//
// Required scopes (any one combination): remote_files:write
func FilesRemoteUpdate(ctx context.Context, c *Client, params *FilesRemoteUpdateParams) (*FilesRemoteUpdateResponse, error) {
	var resp FilesRemoteUpdateResponse
	form := params.values()
	body, err := Do(ctx, c, "files.remote.update", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesRevokePublicURL calls Slack's files.revokePublicURL method.
//
// Required scopes (any one combination): files:write:user
func FilesRevokePublicURL(ctx context.Context, c *Client, params *FilesRevokePublicURLParams) (*FilesRevokePublicURLResponse, error) {
	var resp FilesRevokePublicURLResponse
	form := params.values()
	body, err := Do(ctx, c, "files.revokePublicURL", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesSharedPublicURL calls Slack's files.sharedPublicURL method.
//
// Required scopes (any one combination): files:write:user
func FilesSharedPublicURL(ctx context.Context, c *Client, params *FilesSharedPublicURLParams) (*FilesSharedPublicURLResponse, error) {
	var resp FilesSharedPublicURLResponse
	form := params.values()
	body, err := Do(ctx, c, "files.sharedPublicURL", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// FilesUpload calls Slack's files.upload method.
//
// Required scopes (any one combination): files:write:user
func FilesUpload(ctx context.Context, c *Client, params *FilesUploadParams) (*FilesUploadResponse, error) {
	var resp FilesUploadResponse
	form := params.values()
	body, err := Do(ctx, c, "files.upload", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// MigrationExchange calls Slack's migration.exchange method.
//
// Required scopes (any one combination): tokens.basic
func MigrationExchange(ctx context.Context, c *Client, params *MigrationExchangeParams) (*MigrationExchangeResponse, error) {
	var resp MigrationExchangeResponse
	form := params.values()
	body, err := Do(ctx, c, "migration.exchange", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// OAUTHAccess calls Slack's oauth.access method.
//
// Required scopes (any one combination): none
func OAUTHAccess(ctx context.Context, c *Client, params *OAUTHAccessParams) (*OAUTHAccessResponse, error) {
	var resp OAUTHAccessResponse
	form := params.values()
	body, err := Do(ctx, c, "oauth.access", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// OAUTHToken calls Slack's oauth.token method.
//
// Required scopes (any one combination): none
func OAUTHToken(ctx context.Context, c *Client, params *OAUTHTokenParams) (*OAUTHTokenResponse, error) {
	var resp OAUTHTokenResponse
	form := params.values()
	body, err := Do(ctx, c, "oauth.token", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// OAUTHV2Access calls Slack's oauth.v2.access method.
//
// Required scopes (any one combination): none
func OAUTHV2Access(ctx context.Context, c *Client, params *OAUTHV2AccessParams) (*OAUTHV2AccessResponse, error) {
	var resp OAUTHV2AccessResponse
	form := params.values()
	body, err := Do(ctx, c, "oauth.v2.access", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// PinsAdd calls Slack's pins.add method.
//
// Required scopes (any one combination): pins:write
func PinsAdd(ctx context.Context, c *Client, params *PinsAddParams) (*PinsAddResponse, error) {
	var resp PinsAddResponse
	form := params.values()
	body, err := Do(ctx, c, "pins.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// PinsList calls Slack's pins.list method.
//
// Required scopes (any one combination): pins:read
func PinsList(ctx context.Context, c *Client, params *PinsListParams) (*PinsListResponse, error) {
	var resp PinsListResponse
	form := params.values()
	body, err := Do(ctx, c, "pins.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// PinsRemove calls Slack's pins.remove method.
//
// Required scopes (any one combination): pins:write
func PinsRemove(ctx context.Context, c *Client, params *PinsRemoveParams) (*PinsRemoveResponse, error) {
	var resp PinsRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "pins.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ReactionsAdd calls Slack's reactions.add method.
//
// Required scopes (any one combination): reactions:write
func ReactionsAdd(ctx context.Context, c *Client, params *ReactionsAddParams) (*ReactionsAddResponse, error) {
	var resp ReactionsAddResponse
	form := params.values()
	body, err := Do(ctx, c, "reactions.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ReactionsGet calls Slack's reactions.get method.
//
// Required scopes (any one combination): reactions:read
func ReactionsGet(ctx context.Context, c *Client, params *ReactionsGetParams) (*ReactionsGetResponse, error) {
	var resp ReactionsGetResponse
	form := params.values()
	body, err := Do(ctx, c, "reactions.get", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ReactionsList calls Slack's reactions.list method.
//
// Required scopes (any one combination): reactions:read
func ReactionsList(ctx context.Context, c *Client, params *ReactionsListParams) (*ReactionsListResponse, error) {
	var resp ReactionsListResponse
	form := params.values()
	body, err := Do(ctx, c, "reactions.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ReactionsRemove calls Slack's reactions.remove method.
//
// Required scopes (any one combination): reactions:write
func ReactionsRemove(ctx context.Context, c *Client, params *ReactionsRemoveParams) (*ReactionsRemoveResponse, error) {
	var resp ReactionsRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "reactions.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// RemindersAdd calls Slack's reminders.add method.
//
// Required scopes (any one combination): reminders:write
func RemindersAdd(ctx context.Context, c *Client, params *RemindersAddParams) (*RemindersAddResponse, error) {
	var resp RemindersAddResponse
	form := params.values()
	body, err := Do(ctx, c, "reminders.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// RemindersComplete calls Slack's reminders.complete method.
//
// Required scopes (any one combination): reminders:write
func RemindersComplete(ctx context.Context, c *Client, params *RemindersCompleteParams) (*RemindersCompleteResponse, error) {
	var resp RemindersCompleteResponse
	form := params.values()
	body, err := Do(ctx, c, "reminders.complete", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// RemindersDelete calls Slack's reminders.delete method.
//
// Required scopes (any one combination): reminders:write
func RemindersDelete(ctx context.Context, c *Client, params *RemindersDeleteParams) (*RemindersDeleteResponse, error) {
	var resp RemindersDeleteResponse
	form := params.values()
	body, err := Do(ctx, c, "reminders.delete", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// RemindersInfo calls Slack's reminders.info method.
//
// Required scopes (any one combination): reminders:read
func RemindersInfo(ctx context.Context, c *Client, params *RemindersInfoParams) (*RemindersInfoResponse, error) {
	var resp RemindersInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "reminders.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// RemindersList calls Slack's reminders.list method.
//
// Required scopes (any one combination): reminders:read
func RemindersList(ctx context.Context, c *Client) (*RemindersListResponse, error) {
	var resp RemindersListResponse
	form := url.Values{}
	body, err := Do(ctx, c, "reminders.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// RtmConnect calls Slack's rtm.connect method.
//
// Required scopes (any one combination): rtm:stream
func RtmConnect(ctx context.Context, c *Client, params *RtmConnectParams) (*RtmConnectResponse, error) {
	var resp RtmConnectResponse
	form := params.values()
	body, err := Do(ctx, c, "rtm.connect", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// SearchMessages calls Slack's search.messages method.
//
// Required scopes (any one combination): search:read
func SearchMessages(ctx context.Context, c *Client, params *SearchMessagesParams) (*SearchMessagesResponse, error) {
	var resp SearchMessagesResponse
	form := params.values()
	body, err := Do(ctx, c, "search.messages", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// StarsAdd calls Slack's stars.add method.
//
// Required scopes (any one combination): stars:write
func StarsAdd(ctx context.Context, c *Client, params *StarsAddParams) (*StarsAddResponse, error) {
	var resp StarsAddResponse
	form := params.values()
	body, err := Do(ctx, c, "stars.add", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// StarsList calls Slack's stars.list method.
//
// Required scopes (any one combination): stars:read
func StarsList(ctx context.Context, c *Client, params *StarsListParams) (*StarsListResponse, error) {
	var resp StarsListResponse
	form := params.values()
	body, err := Do(ctx, c, "stars.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// StarsRemove calls Slack's stars.remove method.
//
// Required scopes (any one combination): stars:write
func StarsRemove(ctx context.Context, c *Client, params *StarsRemoveParams) (*StarsRemoveResponse, error) {
	var resp StarsRemoveResponse
	form := params.values()
	body, err := Do(ctx, c, "stars.remove", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// TeamAccessLogs calls Slack's team.accessLogs method.
//
// Required scopes (any one combination): admin
func TeamAccessLogs(ctx context.Context, c *Client, params *TeamAccessLogsParams) (*TeamAccessLogsResponse, error) {
	var resp TeamAccessLogsResponse
	form := params.values()
	body, err := Do(ctx, c, "team.accessLogs", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// TeamBillableInfo calls Slack's team.billableInfo method.
//
// Required scopes (any one combination): admin
func TeamBillableInfo(ctx context.Context, c *Client, params *TeamBillableInfoParams) (*TeamBillableInfoResponse, error) {
	var resp TeamBillableInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "team.billableInfo", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// TeamInfo calls Slack's team.info method.
//
// Required scopes (any one combination): team:read
func TeamInfo(ctx context.Context, c *Client, params *TeamInfoParams) (*TeamInfoResponse, error) {
	var resp TeamInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "team.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// TeamIntegrationLogs calls Slack's team.integrationLogs method.
//
// Required scopes (any one combination): admin
func TeamIntegrationLogs(ctx context.Context, c *Client, params *TeamIntegrationLogsParams) (*TeamIntegrationLogsResponse, error) {
	var resp TeamIntegrationLogsResponse
	form := params.values()
	body, err := Do(ctx, c, "team.integrationLogs", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// TeamProfileGet calls Slack's team.profile.get method.
//
// Required scopes (any one combination): users.profile:read
func TeamProfileGet(ctx context.Context, c *Client, params *TeamProfileGetParams) (*TeamProfileGetResponse, error) {
	var resp TeamProfileGetResponse
	form := params.values()
	body, err := Do(ctx, c, "team.profile.get", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsCreate calls Slack's usergroups.create method.
//
// Required scopes (any one combination): usergroups:write
func UsergroupsCreate(ctx context.Context, c *Client, params *UsergroupsCreateParams) (*UsergroupsCreateResponse, error) {
	var resp UsergroupsCreateResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.create", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsDisable calls Slack's usergroups.disable method.
//
// Required scopes (any one combination): usergroups:write
func UsergroupsDisable(ctx context.Context, c *Client, params *UsergroupsDisableParams) (*UsergroupsDisableResponse, error) {
	var resp UsergroupsDisableResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.disable", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsEnable calls Slack's usergroups.enable method.
//
// Required scopes (any one combination): usergroups:write
func UsergroupsEnable(ctx context.Context, c *Client, params *UsergroupsEnableParams) (*UsergroupsEnableResponse, error) {
	var resp UsergroupsEnableResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.enable", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsList calls Slack's usergroups.list method.
//
// Required scopes (any one combination): usergroups:read
func UsergroupsList(ctx context.Context, c *Client, params *UsergroupsListParams) (*UsergroupsListResponse, error) {
	var resp UsergroupsListResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsUpdate calls Slack's usergroups.update method.
//
// Required scopes (any one combination): usergroups:write
func UsergroupsUpdate(ctx context.Context, c *Client, params *UsergroupsUpdateParams) (*UsergroupsUpdateResponse, error) {
	var resp UsergroupsUpdateResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.update", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsUsersList calls Slack's usergroups.users.list method.
//
// Required scopes (any one combination): usergroups:read
func UsergroupsUsersList(ctx context.Context, c *Client, params *UsergroupsUsersListParams) (*UsergroupsUsersListResponse, error) {
	var resp UsergroupsUsersListResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.users.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsergroupsUsersUpdate calls Slack's usergroups.users.update method.
//
// Required scopes (any one combination): usergroups:write
func UsergroupsUsersUpdate(ctx context.Context, c *Client, params *UsergroupsUsersUpdateParams) (*UsergroupsUsersUpdateResponse, error) {
	var resp UsergroupsUsersUpdateResponse
	form := params.values()
	body, err := Do(ctx, c, "usergroups.users.update", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersConversations calls Slack's users.conversations method.
//
// Required scopes (any one combination): channels:read, groups:read, im:read, mpim:read
func UsersConversations(ctx context.Context, c *Client, params *UsersConversationsParams) (*UsersConversationsResponse, error) {
	var resp UsersConversationsResponse
	form := params.values()
	body, err := Do(ctx, c, "users.conversations", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersDeletePhoto calls Slack's users.deletePhoto method.
//
// Required scopes (any one combination): users.profile:write
func UsersDeletePhoto(ctx context.Context, c *Client) (*UsersDeletePhotoResponse, error) {
	var resp UsersDeletePhotoResponse
	form := url.Values{}
	body, err := Do(ctx, c, "users.deletePhoto", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersGetPresence calls Slack's users.getPresence method.
//
// Required scopes (any one combination): users:read
func UsersGetPresence(ctx context.Context, c *Client, params *UsersGetPresenceParams) (*UsersGetPresenceResponse, error) {
	var resp UsersGetPresenceResponse
	form := params.values()
	body, err := Do(ctx, c, "users.getPresence", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersIdentity calls Slack's users.identity method.
//
// Required scopes (any one combination): identity.basic
func UsersIdentity(ctx context.Context, c *Client) (*UsersIdentityResponse, error) {
	var resp UsersIdentityResponse
	form := url.Values{}
	body, err := Do(ctx, c, "users.identity", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersInfo calls Slack's users.info method.
//
// Required scopes (any one combination): users:read
func UsersInfo(ctx context.Context, c *Client, params *UsersInfoParams) (*UsersInfoResponse, error) {
	var resp UsersInfoResponse
	form := params.values()
	body, err := Do(ctx, c, "users.info", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersList calls Slack's users.list method.
//
// Required scopes (any one combination): users:read
func UsersList(ctx context.Context, c *Client, params *UsersListParams) (*UsersListResponse, error) {
	var resp UsersListResponse
	form := params.values()
	body, err := Do(ctx, c, "users.list", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersLookupByEmail calls Slack's users.lookupByEmail method.
//
// Required scopes (any one combination): users:read.email
func UsersLookupByEmail(ctx context.Context, c *Client, params *UsersLookupByEmailParams) (*UsersLookupByEmailResponse, error) {
	var resp UsersLookupByEmailResponse
	form := params.values()
	body, err := Do(ctx, c, "users.lookupByEmail", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersProfileGet calls Slack's users.profile.get method.
//
// Required scopes (any one combination): users.profile:read
func UsersProfileGet(ctx context.Context, c *Client, params *UsersProfileGetParams) (*UsersProfileGetResponse, error) {
	var resp UsersProfileGetResponse
	form := params.values()
	body, err := Do(ctx, c, "users.profile.get", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersProfileSet calls Slack's users.profile.set method.
//
// Required scopes (any one combination): users.profile:write
func UsersProfileSet(ctx context.Context, c *Client, params *UsersProfileSetParams) (*UsersProfileSetResponse, error) {
	var resp UsersProfileSetResponse
	form := params.values()
	body, err := Do(ctx, c, "users.profile.set", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersSetActive calls Slack's users.setActive method.
//
// Required scopes (any one combination): users:write
func UsersSetActive(ctx context.Context, c *Client) (*UsersSetActiveResponse, error) {
	var resp UsersSetActiveResponse
	form := url.Values{}
	body, err := Do(ctx, c, "users.setActive", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersSetPhoto calls Slack's users.setPhoto method.
//
// Required scopes (any one combination): users.profile:write
func UsersSetPhoto(ctx context.Context, c *Client, params *UsersSetPhotoParams) (*UsersSetPhotoResponse, error) {
	var resp UsersSetPhotoResponse
	form := params.values()
	body, err := Do(ctx, c, "users.setPhoto", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// UsersSetPresence calls Slack's users.setPresence method.
//
// Required scopes (any one combination): users:write
func UsersSetPresence(ctx context.Context, c *Client, params *UsersSetPresenceParams) (*UsersSetPresenceResponse, error) {
	var resp UsersSetPresenceResponse
	form := params.values()
	body, err := Do(ctx, c, "users.setPresence", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ViewsOpen calls Slack's views.open method.
//
// Required scopes (any one combination): none
func ViewsOpen(ctx context.Context, c *Client, params *ViewsOpenParams) (*ViewsOpenResponse, error) {
	var resp ViewsOpenResponse
	form := params.values()
	body, err := Do(ctx, c, "views.open", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ViewsPublish calls Slack's views.publish method.
//
// Required scopes (any one combination): none
func ViewsPublish(ctx context.Context, c *Client, params *ViewsPublishParams) (*ViewsPublishResponse, error) {
	var resp ViewsPublishResponse
	form := params.values()
	body, err := Do(ctx, c, "views.publish", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ViewsPush calls Slack's views.push method.
//
// Required scopes (any one combination): none
func ViewsPush(ctx context.Context, c *Client, params *ViewsPushParams) (*ViewsPushResponse, error) {
	var resp ViewsPushResponse
	form := params.values()
	body, err := Do(ctx, c, "views.push", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// ViewsUpdate calls Slack's views.update method.
//
// Required scopes (any one combination): none
func ViewsUpdate(ctx context.Context, c *Client, params *ViewsUpdateParams) (*ViewsUpdateResponse, error) {
	var resp ViewsUpdateResponse
	form := params.values()
	body, err := Do(ctx, c, "views.update", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// WorkflowsStepCompleted calls Slack's workflows.stepCompleted method.
//
// Required scopes (any one combination): workflow.steps:execute
func WorkflowsStepCompleted(ctx context.Context, c *Client, params *WorkflowsStepCompletedParams) (*WorkflowsStepCompletedResponse, error) {
	var resp WorkflowsStepCompletedResponse
	form := params.values()
	body, err := Do(ctx, c, "workflows.stepCompleted", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// WorkflowsStepFailed calls Slack's workflows.stepFailed method.
//
// Required scopes (any one combination): workflow.steps:execute
func WorkflowsStepFailed(ctx context.Context, c *Client, params *WorkflowsStepFailedParams) (*WorkflowsStepFailedResponse, error) {
	var resp WorkflowsStepFailedResponse
	form := params.values()
	body, err := Do(ctx, c, "workflows.stepFailed", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}

// WorkflowsUpdateStep calls Slack's workflows.updateStep method.
//
// Required scopes (any one combination): workflow.steps:execute
func WorkflowsUpdateStep(ctx context.Context, c *Client, params *WorkflowsUpdateStepParams) (*WorkflowsUpdateStepResponse, error) {
	var resp WorkflowsUpdateStepResponse
	form := params.values()
	body, err := Do(ctx, c, "workflows.updateStep", form, &resp)
	resp.Raw = body
	if err != nil {
		return &resp, err
	}
	return &resp, nil
}
