// Code generated by cmd/gen-api from Slack's Web API OpenAPI 2.0 spec.
// DO NOT EDIT — regenerate with `make api-gen`.

package slackapi

// MethodScopes maps every Slack Web API method to the OAuth scopes Slack
// requires (any one of which is sufficient — Slack's spec lists them as a
// single union via security[0].slackAuth).
//
// Generated from api/specs/slack_web.json.
var MethodScopes = map[string][]string{
	"admin.apps.approve":                                       {"admin.apps:write"},
	"admin.apps.approved.list":                                 {"admin.apps:read"},
	"admin.apps.requests.list":                                 {"admin.apps:read"},
	"admin.apps.restrict":                                      {"admin.apps:write"},
	"admin.apps.restricted.list":                               {"admin.apps:read"},
	"admin.conversations.archive":                              {"admin.conversations:write"},
	"admin.conversations.convertToPrivate":                     {"admin.conversations:write"},
	"admin.conversations.create":                               {"admin.conversations:write"},
	"admin.conversations.delete":                               {"admin.conversations:write"},
	"admin.conversations.disconnectShared":                     {"admin.conversations:write"},
	"admin.conversations.ekm.listOriginalConnectedChannelInfo": {"admin.conversations:read"},
	"admin.conversations.getConversationPrefs":                 {"admin.conversations:read"},
	"admin.conversations.getTeams":                             {"admin.conversations:read"},
	"admin.conversations.invite":                               {"admin.conversations:write"},
	"admin.conversations.rename":                               {"admin.conversations:write"},
	"admin.conversations.restrictAccess.addGroup":              {"admin.conversations:write"},
	"admin.conversations.restrictAccess.listGroups":            {"admin.conversations:read"},
	"admin.conversations.restrictAccess.removeGroup":           {"admin.conversations:write"},
	"admin.conversations.search":                               {"admin.conversations:read"},
	"admin.conversations.setConversationPrefs":                 {"admin.conversations:write"},
	"admin.conversations.setTeams":                             {"admin.conversations:write"},
	"admin.conversations.unarchive":                            {"admin.conversations:write"},
	"admin.emoji.add":                                          {"admin.teams:write"},
	"admin.emoji.addAlias":                                     {"admin.teams:write"},
	"admin.emoji.list":                                         {"admin.teams:read"},
	"admin.emoji.remove":                                       {"admin.teams:write"},
	"admin.emoji.rename":                                       {"admin.teams:write"},
	"admin.inviteRequests.approve":                             {"admin.invites:write"},
	"admin.inviteRequests.approved.list":                       {"admin.invites:read"},
	"admin.inviteRequests.denied.list":                         {"admin.invites:read"},
	"admin.inviteRequests.deny":                                {"admin.invites:write"},
	"admin.inviteRequests.list":                                {"admin.invites:read"},
	"admin.teams.admins.list":                                  {"admin.teams:read"},
	"admin.teams.create":                                       {"admin.teams:write"},
	"admin.teams.list":                                         {"admin.teams:read"},
	"admin.teams.owners.list":                                  {"admin.teams:read"},
	"admin.teams.settings.info":                                {"admin.teams:read"},
	"admin.teams.settings.setDefaultChannels":                  {"admin.teams:write"},
	"admin.teams.settings.setDescription":                      {"admin.teams:write"},
	"admin.teams.settings.setDiscoverability":                  {"admin.teams:write"},
	"admin.teams.settings.setIcon":                             {"admin.teams:write"},
	"admin.teams.settings.setName":                             {"admin.teams:write"},
	"admin.usergroups.addChannels":                             {"admin.usergroups:write"},
	"admin.usergroups.addTeams":                                {"admin.teams:write"},
	"admin.usergroups.listChannels":                            {"admin.usergroups:read"},
	"admin.usergroups.removeChannels":                          {"admin.usergroups:write"},
	"admin.users.assign":                                       {"admin.users:write"},
	"admin.users.invite":                                       {"admin.users:write"},
	"admin.users.list":                                         {"admin.users:read"},
	"admin.users.remove":                                       {"admin.users:write"},
	"admin.users.session.invalidate":                           {"admin.users:write"},
	"admin.users.session.reset":                                {"admin.users:write"},
	"admin.users.setAdmin":                                     {"admin.users:write"},
	"admin.users.setExpiration":                                {"admin.users:write"},
	"admin.users.setOwner":                                     {"admin.users:write"},
	"admin.users.setRegular":                                   {"admin.users:write"},
	"api.test":                                                 {"none"},
	"apps.event.authorizations.list":                           {"authorizations:read"},
	"apps.permissions.info":                                    {"none"},
	"apps.permissions.request":                                 {"none"},
	"apps.permissions.resources.list":                          {"none"},
	"apps.permissions.scopes.list":                             {"none"},
	"apps.permissions.users.list":                              {"none"},
	"apps.permissions.users.request":                           {"none"},
	"apps.uninstall":                                           {"none"},
	"auth.revoke":                                              {"none"},
	"auth.test":                                                {"none"},
	"bots.info":                                                {"users:read"},
	"calls.add":                                                {"calls:write"},
	"calls.end":                                                {"calls:write"},
	"calls.info":                                               {"calls:read"},
	"calls.participants.add":                                   {"calls:write"},
	"calls.participants.remove":                                {"calls:write"},
	"calls.update":                                             {"calls:write"},
	"chat.delete":                                              {"chat:write:bot", "chat:write:user"},
	"chat.deleteScheduledMessage":                              {"chat:write:bot", "chat:write:user"},
	"chat.getPermalink":                                        {"none"},
	"chat.meMessage":                                           {"chat:write:bot", "chat:write:user"},
	"chat.postEphemeral":                                       {"chat:write:bot", "chat:write:user"},
	"chat.postMessage":                                         {"chat:write:bot", "chat:write:user"},
	"chat.scheduleMessage":                                     {"chat:write:bot", "chat:write:user"},
	"chat.scheduledMessages.list":                              {"none"},
	"chat.unfurl":                                              {"links:write"},
	"chat.update":                                              {"chat:write:bot", "chat:write:user"},
	"conversations.archive":                                    {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.close":                                      {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.create":                                     {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.history":                                    {"channels:history", "groups:history", "im:history", "mpim:history"},
	"conversations.info":                                       {"channels:read", "groups:read", "im:read", "mpim:read"},
	"conversations.invite":                                     {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.join":                                       {"channels:write"},
	"conversations.kick":                                       {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.leave":                                      {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.list":                                       {"channels:read", "groups:read", "im:read", "mpim:read"},
	"conversations.mark":                                       {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.members":                                    {"channels:read", "groups:read", "im:read", "mpim:read"},
	"conversations.open":                                       {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.rename":                                     {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.replies":                                    {"channels:history", "groups:history", "im:history", "mpim:history"},
	"conversations.setPurpose":                                 {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.setTopic":                                   {"channels:write", "groups:write", "im:write", "mpim:write"},
	"conversations.unarchive":                                  {"channels:write", "groups:write", "im:write", "mpim:write"},
	"dialog.open":                                              {"none"},
	"dnd.endDnd":                                               {"dnd:write"},
	"dnd.endSnooze":                                            {"dnd:write"},
	"dnd.info":                                                 {"dnd:read"},
	"dnd.setSnooze":                                            {"dnd:write"},
	"dnd.teamInfo":                                             {"dnd:read"},
	"emoji.list":                                               {"emoji:read"},
	"files.comments.delete":                                    {"files:write:user"},
	"files.delete":                                             {"files:write:user"},
	"files.info":                                               {"files:read"},
	"files.list":                                               {"files:read"},
	"files.remote.add":                                         {"remote_files:write"},
	"files.remote.info":                                        {"remote_files:read"},
	"files.remote.list":                                        {"remote_files:read"},
	"files.remote.remove":                                      {"remote_files:write"},
	"files.remote.share":                                       {"remote_files:share"},
	"files.remote.update":                                      {"remote_files:write"},
	"files.revokePublicURL":                                    {"files:write:user"},
	"files.sharedPublicURL":                                    {"files:write:user"},
	"files.upload":                                             {"files:write:user"},
	"migration.exchange":                                       {"tokens.basic"},
	"oauth.access":                                             {"none"},
	"oauth.token":                                              {"none"},
	"oauth.v2.access":                                          {"none"},
	"pins.add":                                                 {"pins:write"},
	"pins.list":                                                {"pins:read"},
	"pins.remove":                                              {"pins:write"},
	"reactions.add":                                            {"reactions:write"},
	"reactions.get":                                            {"reactions:read"},
	"reactions.list":                                           {"reactions:read"},
	"reactions.remove":                                         {"reactions:write"},
	"reminders.add":                                            {"reminders:write"},
	"reminders.complete":                                       {"reminders:write"},
	"reminders.delete":                                         {"reminders:write"},
	"reminders.info":                                           {"reminders:read"},
	"reminders.list":                                           {"reminders:read"},
	"rtm.connect":                                              {"rtm:stream"},
	"search.messages":                                          {"search:read"},
	"stars.add":                                                {"stars:write"},
	"stars.list":                                               {"stars:read"},
	"stars.remove":                                             {"stars:write"},
	"team.accessLogs":                                          {"admin"},
	"team.billableInfo":                                        {"admin"},
	"team.info":                                                {"team:read"},
	"team.integrationLogs":                                     {"admin"},
	"team.profile.get":                                         {"users.profile:read"},
	"usergroups.create":                                        {"usergroups:write"},
	"usergroups.disable":                                       {"usergroups:write"},
	"usergroups.enable":                                        {"usergroups:write"},
	"usergroups.list":                                          {"usergroups:read"},
	"usergroups.update":                                        {"usergroups:write"},
	"usergroups.users.list":                                    {"usergroups:read"},
	"usergroups.users.update":                                  {"usergroups:write"},
	"users.conversations":                                      {"channels:read", "groups:read", "im:read", "mpim:read"},
	"users.deletePhoto":                                        {"users.profile:write"},
	"users.getPresence":                                        {"users:read"},
	"users.identity":                                           {"identity.basic"},
	"users.info":                                               {"users:read"},
	"users.list":                                               {"users:read"},
	"users.lookupByEmail":                                      {"users:read.email"},
	"users.profile.get":                                        {"users.profile:read"},
	"users.profile.set":                                        {"users.profile:write"},
	"users.setActive":                                          {"users:write"},
	"users.setPhoto":                                           {"users.profile:write"},
	"users.setPresence":                                        {"users:write"},
	"views.open":                                               {"none"},
	"views.publish":                                            {"none"},
	"views.push":                                               {"none"},
	"views.update":                                             {"none"},
	"workflows.stepCompleted":                                  {"workflow.steps:execute"},
	"workflows.stepFailed":                                     {"workflow.steps:execute"},
	"workflows.updateStep":                                     {"workflow.steps:execute"},
}

// AllScopes returns every scope referenced by any method, deduplicated.
func AllScopes() []string {
	seen := map[string]bool{}
	out := make([]string, 0, 64)
	for _, scopes := range MethodScopes {
		for _, s := range scopes {
			if seen[s] {
				continue
			}
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// ScopesForMethods returns the union of scopes for the given methods.
func ScopesForMethods(methods []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, m := range methods {
		for _, s := range MethodScopes[m] {
			if seen[s] {
				continue
			}
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}
